modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT License"

[[mods]]
modId = "fightorflight"
version = "0.7.5"
displayName = "Cobblemon Fight or Flight"
authors = "rufia,LyquidQrystal"
description = '''
Makes Cobblemon run away or fight back in response to a player attack or failed capture
'''

[[dependencies.fightorflight]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.fightorflight]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fightorflight]]
modId = "cobblemon"
type = "required"
versionRange = "[1.6.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fightorflight]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "fightorflight.mixins_common.json"
